#!/usr/bin/bash

echo "[Audit Machine]"
echo
echo "[Nom de l'Hôte]"
hostname
echo
echo "[Version du Noyau]"
uname -a
echo
echo "[Date du jour]"
date
echo
echo "[Auteur]"
whoami
echo
echo "[Nb de PID]"
ps -ef |wc -l
echo
echo "[RAM Disponible]"
free -h
echo
echo "[Stockage Disk Disponible]"
df -h -t ext4
